### ISSUE TITLE
New Page: Admin Page - Teams

### ISSUE THREAD

**Issue by iNovus-Solutions** [samwalton26/mirra#11]
# @samwalton26 
New page or section to modify/create teams
A user can/should be assigned as a team leader
A new user role to be added "Leader" 
They would have the same access as admins other than they can only modify users/chars from that team

**Comment by iNovus-Solutions** [comment]
Thinking about it - We would need to have the collection "TEAMS" and a string with the client name and then an array underneath with the team names

**Comment by samwalton26** [comment]
pull request #19 closes this
